### ISSUE TITLE
RPC Timeout kills docker container

### ISSUE THREAD

**Issue by kevinejohn** [interplanaria/planaria#2]
When running an empty planaria write project from block 1 I keep getting RPC timeouts after about every ~1k blocks that kills the entire docker container. The bitcoind is running on the same machine and runs with the flags `rpcworkqueue=512` and `rpcthreads=64`.

```
RPC BEGIN 2298 Tue Mar 12 2019 23:20:11 GMT+0000 (Coordinated Universal Time)
Err =  Error: Bitcoin JSON-RPC: Request Error: connect ETIMEDOUT 192.168.1.20:8332
    at ClientRequest.<anonymous> (/planaria/node_modules/bitcoind-rpc/lib/index.js:113:15)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
/planaria/bit.js:54
          throw new Error(err)
          ^

Error: Error: Bitcoin JSON-RPC: Request Error: connect ETIMEDOUT 192.168.1.20:8332
    at /planaria/bit.js:54:17
    at ClientRequest.<anonymous> (/planaria/node_modules/bitcoind-rpc/lib/index.js:116:7)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-03-12T23:22:22.510+0000 I NETWORK  [conn2] end connection 127.0.0.1:56822 (0 connections now open)
Exited 0
```

**Comment by carpemer** [comment]
+1
Meet the same issue when I try to crawl the remote nodes.
Not sure what is the best practice of rpc retry in nodejs.
