### ISSUE TITLE
Cannot run pc start

### ISSUE THREAD

**Issue by KaKeimei** [interplanaria/planaria#6]
i am running a node under ubuntu 18.04 and cannot run pc start.
i got an error message as follows:

```
# npm install...

> zeromq@5.1.0 install /planaria/node_modules/interlevel/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)




> leveldown@4.0.2 install /planaria/node_modules/leveldown
> prebuild-install || node-gyp rebuild


> zeromq@4.6.0 install /planaria/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install getaddrinfo EAI_AGAIN github.com github.com:443

{ Error: getaddrinfo EAI_AGAIN github.com github.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'github.com',
  host: 'github.com',
  port: 443 }
npm WARN planaria@0.0.1 No description
npm WARN planaria@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T05_48_18_089Z-debug.log
Exited 0
```

then i got into docker container to see detailed information ,i got this :

```
13592 silly saveTree `-- zeromq@4.6.0
13592 silly saveTree   `-- prebuild-install@2.5.3
13592 silly saveTree     +-- expand-template@1.1.1
13592 silly saveTree     +-- minimist@1.2.0
13592 silly saveTree     `-- pump@2.0.1
13593 warn planaria@0.0.1 No description
13594 warn planaria@0.0.1 No repository field.
13595 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
13596 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
13597 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
13597 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
13597 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
13597 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
13598 verbose stack Error: zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
13598 verbose stack Exit status 1
13598 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13598 verbose stack     at EventEmitter.emit (events.js:182:13)
13598 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13598 verbose stack     at ChildProcess.emit (events.js:182:13)
13598 verbose stack     at maybeClose (internal/child_process.js:962:16)
13598 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13599 verbose pkgid zeromq@4.6.0
13600 verbose cwd /planaria
13601 verbose Linux 4.15.0-1035-aws
13602 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
13603 verbose node v10.10.0
13604 verbose npm  v6.4.1
13605 error code ELIFECYCLE
13606 error errno 1
13607 error zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
13607 error Exit status 1
13608 error Failed at the zeromq@4.6.0 install script.
13608 error This is probably not a problem with npm. There is likely additional logging output above.
13609 verbose exit [ 1, true ]
```

**Comment by KaKeimei** [comment]
successful under ubuntu 16.04

**Comment by ddomizzisg** [comment]
Did you find any solution?

**Comment by stevenzeiler** [comment]
Looks like you don't have zeromq installed.
